batch_size: 1
checkpoint: true
ckpt_freq: 100
ckpt_only_lora: true
data:
  data: ''
  eval_instruct_data: ''
  instruct:
    dynamic_chunk_fn_call: true
    shuffle: true
  instruct_data: /home/amt42/projects/mistral-finetune/data/corrected_data.jsonl
  shuffle: false
eval_freq: 100
log_freq: 1
lora:
  dropout: 0.0
  enable: true
  rank: 64
  scaling: 2.0
max_norm: 1.0
max_steps: 300
mlflow:
  experiment_name: null
  tracking_uri: null
model_id_or_path: /home/amt42/projects/mistral-finetune/mistral-models/
no_ckpt: false
no_eval: true
num_ckpt_keep: 3
num_microbatches: 1
optim:
  lr: 6.0e-05
  pct_start: 0.05
  weight_decay: 0.1
run_dir: /home/amt42/projects/utils
seed: 0
seq_len: 32768
wandb:
  key: da7e19797ebd7fecf792f0ce4ccb407354f18d37
  offline: false
  project: CHEMISTral7b-ft
  run_name: runseed44
world_size: 1
